services:
  accounting-database:
    image: postgres
    ports:
      - "7425:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: accounting_is_fun!
    volumes:
      - accounting_data:/var/lib/postgresql/data

volumes:
  accounting_data: